/*
 Copyright 2020 The Knative Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	solarv1alpha1 "my.dev/solar-system/pkg/apis/solar/v1alpha1"
	versioned "my.dev/solar-system/pkg/client/clientset/versioned"
	internalinterfaces "my.dev/solar-system/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "my.dev/solar-system/pkg/client/listers/solar/v1alpha1"
)

// StarInformer provides access to a shared informer and lister for
// Stars.
type StarInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StarLister
}

type starInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStarInformer constructs a new informer for Star type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStarInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStarInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStarInformer constructs a new informer for Star type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStarInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().Stars(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().Stars(namespace).Watch(options)
			},
		},
		&solarv1alpha1.Star{},
		resyncPeriod,
		indexers,
	)
}

func (f *starInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStarInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *starInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&solarv1alpha1.Star{}, f.defaultInformer)
}

func (f *starInformer) Lister() v1alpha1.StarLister {
	return v1alpha1.NewStarLister(f.Informer().GetIndexer())
}
